sistema_mvc/models/produto.py
class Produto:

    # POO -> Construtor
    def __init__(self, id=None, nome=None, preco=None):
        self.id = id
        self.nome = nome
        self.preco = preco

    @staticmethod
    def listar(myslq):
        cursor = myslq.connection.cursor()
        cursor.execute("SELECT id, nome, preco FROM produtos")
        resultados = cursor.fetchall()
        cursor.close()
        return [Produto(id=r[0], nome=r[1], preco=r[2]) for r in resultados]
    
    def salvar(self, mysql):
        cursor = mysql.connection.cursor()
        cursor.execute("INSERT INTO produtos (nome, preco) VALUES (%s, %s)", (self.nome, self.preco))
        mysql.connection.commit()
        cursor.close()

    @staticmethod
    def buscar_por_id(mysql, id):
        cursor = mysql.connection.cursor()
        cursor.execute("SELECT id, nome, preco FROM produtos WHERE id = %s", (id,))
        resultado = cursor.fetchone()
        cursor.close()
        if resultado:
            return Produto(id=resultado[0], nome=resultado[1], preco=resultado[2])
        return None
    
    def atualizar(self, mysql):
        cursor = mysql.connection.cursor()
        cursor.execute("UPDATE produtos SET nome = %s, preco = %s WHERE id = %s", (self.nome, self.preco, self.id))
        mysql.connection.commit()
        cursor.close()

    def deletar(mysql, id):
        cursor = mysql.connection.cursor()
        cursor.execute("DELETE FROM produtos WHERE id = %s", (id,))
        mysql.connection.commit()
        cursor.close()

sistema_mvc/app.py
from flask import Flask
from flask_mysqldb import MySQL
from controllers.produto_controller import produto_bp
import config

app = Flask(__name__)
app.config.from_object(config)

mysql = MySQL(app)

app.mysql = mysql

app.register_blueprint(produto_bp)

if __name__ == '__main__':
    app.run(debug=True)
    

sistema_mvc/controllers/produto_controller.py
from flask import Blueprint, current_app, redirect,render_template, request, url_for
from models.produto import Produto

produto_bp = Blueprint('produto', __name__)

@produto_bp.route('/')
def index():
    produtos = Produto.listar(current_app.mysql)
    return render_template('index.html', produtos=produtos)

@produto_bp.route('/criar', methods=['GET', 'POST'])
def criar():
    if request.method == 'POST':
        nome = request.form['nome']
        preco = request.form['preco']
        Produto.salvar(Produto(None, nome, preco), current_app.mysql)
        return redirect(url_for('produto.index'))
    return render_template('criar.html')

@produto_bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar(id):
    if request.method == 'POST':
        nome = request.form['nome']
        preco = request.form['preco']
        Produto.atualizar(Produto(id, nome, preco), current_app.mysql)
        return redirect(url_for('produto.index'))
    prod = Produto.buscar_por_id(current_app.mysql, id)
    return render_template('editar.html', produto=prod)

@produto_bp.route('/deletar/<int:id>')
def deletar(id):
    Produto.deletar(current_app.mysql, id)
    return redirect(url_for('produto.index'))

sistema_mvc/templates/criar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Produto</title>
    <link rel="stylesheet" href="../static/criar.css">
</head>
<body>
    <h1>Criar Produto</h1>
    <form method="post" class="form-criar">
        Nome: <input type="text" name="nome" placeholder="Produto aqui"/> <br>
        Preço: <input type="text" name="preco" placeholder="Preço aqui"/> <br>
        <button type="submit">Salvar</button>
    </form>
    
    <a href="/" class="link-voltar">Voltar</a>

</body>
</html>

sistema_mvc/templates/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Produto</title>
    <link rel="stylesheet" href="../static/editar.css">
</head>
<body>
    <h1>Editar Produto</h1>

    <form method="post" class="form-editar">
        Nome: <input value="{{ produto['nome'] }}" type="text" name="nome"/> <br>
        Preço: <input value="{{ produto['preco'] }}" type="number" name="preco"/> <br>
        <button type="submit">Salvar</button>
    </form>

    <a href="/" class="link-voltar">Voltar</a>
</body>
</html>

sistema_mvc/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Produto</title>
    <link rel="stylesheet" href="../static/index.css">
</head>
<body>
    <h1>Lista de Produtos</h1>
    <a href="/criar" class="link-novo-produto">Novo Produto</a>

    <ul class="container">
        {% for produto in produtos %}
            <li>
                {{ produto['nome'] }} - {{ produto['preco'] }}
                <a class="btn-editar" href="{{ url_for('produto.editar', id=produto['id']) }}">
                <button >
                    Editar
                </button>
            </a>
            <a class="btn-deletar" href="{{ url_for('produto.deletar', id=produto['id']) }}">
                <button>
                    Deletar
                </button>
            </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>